
# TensorFlow 2 Exercises for Basic Tensor Manipulation

This notebook provides a set of exercises designed to familiarize you with the basics of tensor manipulation in TensorFlow 2,
which is essential for handling Large Language Models (LLMs).

## Contents
1. Tensor Basics
2. Tensor Operations
3. Manipulating Tensor Shapes
4. Indexing and Slicing
5. Broadcasting
6. Gradients and Differentiation
7. Simple Neural Network Components
8. Data Loading and Preprocessing

Each section will include a brief explanation followed by practical exercises.



## 1. Tensor Basics

**Objective**: Understand how to create tensors, and learn about their types and shapes.

**Exercises**:
1. Create a scalar tensor (0-D tensor) with a specific value.
2. Create a 1-D tensor (vector) with 5 elements.
3. Create a 2-D tensor (matrix) of shape (3, 3).
4. Find the data type (`dtype`) of the tensors created above.
5. Convert a numpy array to a TensorFlow tensor.


In [7]:
import tensorflow as tf
import numpy as np

scalar_tensor = tf.constant(5)
print("Scalar Tensor:")
print(scalar_tensor)


vector = tf.constant([1, 2, 3, 4, 5])

print("1-D Tensor (Vector) with 5 elements:")
print(vector)

matrix = tf.constant([[1, 2, 3],
                      [4, 5, 6],
                      [7, 8, 9]])

print("2-D Tensor (Matrix) of shape (3, 3):")
print(matrix)

matrix_dtype = matrix.dtype

print("Data type (dtype) of the 2-D tensor (matrix):")
print(matrix_dtype)

numpy_array = np.array([[1, 2, 3],
                        [4, 5, 6]])

# Convert the NumPy array to a TensorFlow tensor
tensor_from_numpy = tf.convert_to_tensor(numpy_array)

print("TensorFlow Tensor from NumPy array:")
print(tensor_from_numpy)


Scalar Tensor:
tf.Tensor(5, shape=(), dtype=int32)
1-D Tensor (Vector) with 5 elements:
tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)
2-D Tensor (Matrix) of shape (3, 3):
tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)
Data type (dtype) of the 2-D tensor (matrix):
<dtype: 'int32'>
TensorFlow Tensor from NumPy array:
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int64)



## 2. Tensor Operations

**Objective**: Perform basic arithmetic operations and learn some advanced operations.

**Exercises**:
1. Add, subtract, multiply, and divide two tensors.
2. Compute the mean and standard deviation of a tensor.
3. Apply a non-linear activation function (like ReLU) to a tensor.
4. Perform matrix multiplication between two 2-D tensors.


In [8]:
import tensorflow as tf

# Define two TensorFlow tensors
tensor1 = tf.constant([[1, 2, 3],
                       [4, 5, 6]])

tensor2 = tf.constant([[7, 8, 9],
                       [10, 11, 12]])

# Addition
addition_result = tf.add(tensor1, tensor2)

# Subtraction
subtraction_result = tf.subtract(tensor1, tensor2)

# Multiplication
multiplication_result = tf.multiply(tensor1, tensor2)

# Division
division_result = tf.divide(tensor1, tensor2)

# Print results
print("Addition Result:")
print(addition_result)
print("\nSubtraction Result:")
print(subtraction_result)
print("\nMultiplication Result:")
print(multiplication_result)
print("\nDivision Result:")
print(division_result)

Addition Result:
tf.Tensor(
[[ 8 10 12]
 [14 16 18]], shape=(2, 3), dtype=int32)

Subtraction Result:
tf.Tensor(
[[-6 -6 -6]
 [-6 -6 -6]], shape=(2, 3), dtype=int32)

Multiplication Result:
tf.Tensor(
[[ 7 16 27]
 [40 55 72]], shape=(2, 3), dtype=int32)

Division Result:
tf.Tensor(
[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]], shape=(2, 3), dtype=float64)


In [10]:
import tensorflow as tf

# Define a TensorFlow tensor (convert integer values to floating-point)
tensor = tf.constant([[1.0, 2.0, 3.0],
                      [4.0, 5.0, 6.0]])

# Compute the mean
mean = tf.reduce_mean(tensor)

# Compute the standard deviation
std_dev = tf.math.reduce_std(tf.cast(tensor, tf.float32))

# Print results
print("Mean of the tensor:", mean.numpy())
print("Standard deviation of the tensor:", std_dev.numpy())


Mean of the tensor: 3.5
Standard deviation of the tensor: 1.7078252


In [11]:
tensor = tf.constant([-1.0, 2.0, -3.0, 4.0, -5.0])

# Apply ReLU activation function
relu_result = tf.nn.relu(tensor)

# Print the result
print("Result after applying ReLU activation:")
print(relu_result)

Result after applying ReLU activation:
tf.Tensor([0. 2. 0. 4. 0.], shape=(5,), dtype=float32)


In [12]:
import tensorflow as tf

# Define two 2-D tensors
tensor1 = tf.constant([[1, 2],
                       [3, 4]])

tensor2 = tf.constant([[5, 6],
                       [7, 8]])

# Perform matrix multiplication
result = tf.matmul(tensor1, tensor2)

# Print the result
print("Result of matrix multiplication:")
print(result)


Result of matrix multiplication:
tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)



## 3. Manipulating Tensor Shapes

**Objective**: Learn how to reshape and transpose tensors.

**Exercises**:
1. Create a tensor of shape (4, 4), then reshape it to (2, 8).
2. Transpose a 2-D tensor.
3. Flatten a 3-D tensor to a 1-D tensor.


In [16]:
import tensorflow as tf

# Create a tensor of shape (4, 4)
tensor = tf.constant([[1, 2, 3, 4],
                      [5, 6, 7, 8],
                      [9, 10, 11, 12],
                      [13, 14, 15, 16]])

# Reshape the tensor to shape (2, 8)
reshaped_tensor = tf.reshape(tensor, (2, 8))

# Print the original and reshaped tensors
print("Original Tensor (shape 4x4):")
print(tensor)
print("\nReshaped Tensor (shape 2x8):")
print(reshaped_tensor)

tensor = tf.constant([[1, 2, 3],
                      [4, 5, 6]])

# Transpose the tensor
transposed_tensor = tf.transpose(tensor)

# Print the original and transposed tensors
print("Original Tensor:")
print(tensor)
print("\nTransposed Tensor:")
print(transposed_tensor)

tensor_3d = tf.constant([[[1, 2, 3],
                          [4, 5, 6]],

                         [[7, 8, 9],
                          [10, 11, 12]]])

# Flatten the 3-D tensor to a 1-D tensor
flattened_tensor = tf.reshape(tensor_3d, [-1])

# Print the original and flattened tensors
print("Original 3-D Tensor:")
print(tensor_3d)
print("\nFlattened 1-D Tensor:")
print(flattened_tensor)

Original Tensor (shape 4x4):
tf.Tensor(
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]], shape=(4, 4), dtype=int32)

Reshaped Tensor (shape 2x8):
tf.Tensor(
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]], shape=(2, 8), dtype=int32)
Original Tensor:
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)

Transposed Tensor:
tf.Tensor(
[[1 4]
 [2 5]
 [3 6]], shape=(3, 2), dtype=int32)
Original 3-D Tensor:
tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]], shape=(2, 2, 3), dtype=int32)

Flattened 1-D Tensor:
tf.Tensor([ 1  2  3  4  5  6  7  8  9 10 11 12], shape=(12,), dtype=int32)



## 4. Indexing and Slicing

**Objective**: Access specific elements or slices of a tensor.

**Exercises**:
1. Extract a specific element from a tensor.
2. Slice a portion of a tensor.
3. Use boolean tensor indexing to filter elements.


In [3]:
import tensorflow as tf

# Create a sample tensor (2D array)
tensor = tf.constant([[1, 2, 3],
                      [4, 5, 6],
                      [7, 8, 9]])

# Specify the indices of the element you want to extract
row_index = 1
column_index = 2

# Extract the element at the specified indices
element = tensor[row_index, column_index]

# Print the value of the element
print("Element at ({}, {}):".format(row_index, column_index), element.numpy())


Element at (1, 2): 6


In [6]:
import tensorflow as tf

# Create a sample tensor (2D array)
tensor = tf.constant([[1, 2, 3],
                      [4, 5, 6],
                      [7, 8, 9]])

# Slice a portion of the tensor
# Syntax: tensor[start_row:end_row, start_column:end_column]
subset = tensor[0:2, 1:3]

# Print the subset
print("Subset of the tensor:")
print(subset)


Subset of the tensor:
tf.Tensor(
[[2 3]
 [5 6]], shape=(2, 2), dtype=int32)


In [5]:
import tensorflow as tf

# Create a sample tensor
tensor = tf.constant([[1, 2, 3],
                      [4, 5, 6],
                      [7, 8, 9]])

# Define a boolean condition to filter elements greater than 5
condition = tensor > 5

# Apply the boolean condition to filter elements
filtered_elements = tf.boolean_mask(tensor, condition)

# Print the filtered elements
print("Filtered elements:")
print(filtered_elements.numpy())


Filtered elements:
[6 7 8 9]



## 5. Broadcasting

**Objective**: Understand and apply broadcasting rules in tensor operations.

**Exercises**:
1. Perform an element-wise addition between tensors of different shapes.
2. Broadcast a smaller tensor to match the shape of a larger tensor in an operation.



## 6. Gradients and Differentiation

**Objective**: Basic introduction to automatic differentiation.

**Exercises**:
1. Use `tf.GradientTape` to compute derivatives.
2. Find the gradient of a simple function with respect to one of its inputs.



## 7. Data Loading and Preprocessing

**Objective**: Use `tf.data` for efficient data handling.

**Exercises**:
1. Create a simple dataset using `tf.data.Dataset`.
2. Apply a transformation (like mapping) to the dataset.
3. Batch and shuffle the dataset.
